import { Listing } from '@/types/listing';

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Grand Garden Events Center',
    slug: 'grand-garden-events-center-1',
    description: 'Beautiful outdoor venue perfect for weddings',
    category: 'event_venue',
    location: 'Karen, Nairobi',
    address: '123 Karen Road',
    county: 'Nairobi',
    city: 'Nairobi',
    capacity: 300,
    basePrice: '50000',
    coverPhoto: 'https://images.unsplash.com/photo-1519167758481-83f29da8dd8f',
    photos: ['https://images.unsplash.com/photo-1519167758481-83f29da8dd8f'],
    amenities: ['parking', 'wifi', 'catering'],
    status: 'active',
    rating: 4.8,
    vendor: { id: 'v1', businessName: 'Golden Events' },
  },
  {
    id: '2',
    title: 'Elegant Waterfront Venue',
    slug: 'elegant-waterfront-venue-2',
    description: 'Stunning waterfront location',
    category: 'event_venue',
    location: 'Mombasa',
    address: '456 Beach Road',
    capacity: 500,
    basePrice: '75000',
    coverPhoto: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3',
    photos: ['https://images.unsplash.com/photo-1464366400600-7168b8af9bc3'],
    amenities: ['parking', 'ocean view'],
    status: 'active',
    rating: 4.9,
    vendor: { id: 'v2', businessName: 'Coastal Events' },
  },
  {
    id: '3',
    title: 'Modern Conference Hall',
    slug: 'modern-conference-hall-3',
    description: 'Professional conference space',
    category: 'event_venue',
    location: 'Westlands, Nairobi',
    address: '789 Waiyaki Way',
    capacity: 200,
    basePrice: '40000',
    coverPhoto: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678',
    photos: ['https://images.unsplash.com/photo-1505373877841-8d25f7d46678'],
    amenities: ['projector', 'wifi'],
    status: 'active',
    rating: 4.7,
    vendor: { id: 'v3', businessName: 'Corporate Venues' },
  },
  {
    id: '4',
    title: 'Premium Catering Services',
    slug: 'premium-catering-services-4',
    description: 'High-end catering for all events',
    category: 'catering',
    location: 'Nairobi CBD',
    address: 'Central Business District',
    basePrice: '15000',
    coverPhoto: 'https://images.unsplash.com/photo-1555244162-803834f70033',
    photos: ['https://images.unsplash.com/photo-1555244162-803834f70033'],
    amenities: ['buffet', 'waiters'],
    status: 'active',
    rating: 4.6,
    vendor: { id: 'v4', businessName: 'Deluxe Catering' },
  },
  {
    id: '5',
    title: 'Luxury Hotel Suite',
    slug: 'luxury-hotel-suite-5',
    description: 'Premium accommodation',
    category: 'accommodation',
    location: 'Kilimani, Nairobi',
    address: 'Kilimani Estate',
    basePrice: '8000',
    coverPhoto: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
    photos: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
    amenities: ['pool', 'gym'],
    status: 'active',
    rating: 4.8,
    vendor: { id: 'v5', businessName: 'Luxury Stays' },
  },
  {
    id: '6',
    title: 'Garden Party Venue',
    slug: 'garden-party-venue-6',
    description: 'Beautiful garden setting',
    category: 'event_venue',
    location: 'Runda, Nairobi',
    address: 'Runda Estate',
    capacity: 150,
    basePrice: '35000',
    coverPhoto: 'https://images.unsplash.com/photo-1530103043960-ef38714abb15',
    photos: ['https://images.unsplash.com/photo-1530103043960-ef38714abb15'],
    amenities: ['garden', 'parking'],
    status: 'active',
    rating: 4.5,
    vendor: { id: 'v6', businessName: 'Garden Events' },
  },
];